#!/bin/zsh

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES="$HOME/Dev/dotfiles"

# display how long all tasks over 10 seconds take
export REPORTTIME=10

[[ -e ~/.terminfo ]] && export TERMINFO_DIRS=~/.terminfo:/usr/share/terminfo

# your project folder that we can `c [tab]` to
export PROJECTS="$HOME/Code"

# your default editor
export EDITOR='code'

# Ensure languages are set
#export LANG=en_US.UTF-8
#export LANGUAGE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8

export TERM=xterm-256color

#source $DOTFILES/zshell/profile.d/exports

source $HOME/.zsh_exports

if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# initialize autocomplete
#autoload -U compinit add-zsh-hook
#compinit

source ~/.antibody_plugins.sh

# Load ~/.aliases, ~/.functions, ~/.fun, and ~/.extra
for file in ~/.{zsh_aliases,zsh_functions,zsh_extra}; do
    [ -r "$file" ] && source "$file"
done
unset file

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
