#!/bin/bash

# your project folder that we can `c [tab]` to
export PROJECTS="$HOME/Dev"

# your default editor
export EDITOR='atom'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"


export GOPATH="$PROJECTS/Go"
export PATH="$PATH:$GOPATH/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
